#!/bin/sh
#service wpanet
WL=wlan0

case "$1" in
  start)
    for IF in $WL
      do
        wpa_supplicant -Dwext -i $IF -c /etc/wpa/$IF.conf -B
        wpa_cli -i $IF -a /sbin/wpa_dhcp -B
      done
  ;;
  stop)
    for IF in $WL
      do
         /sbin/wpa_dhcp $IF stop
      done
  ;;
  *help)
    echo "Usage: $0 start | stop to start or stop all interfaces"
    echo "Use wpa_dhcp if0 stop to stop one interface"
  ;;
esac

