#!/bin/sh
source /etc/conf.d/wpanet

case "$1" in
  start)
    for IF in $IFACES
      do
        wpa_supplicant ${DRIVER:--Dwext} -i $IF -c ${WPA_CFG:-/etc/wpa/$IF.conf} -B
        wpa_cli -i $IF -a /sbin/wpa_dhcp -B
      done
  ;;
  stop)
    for IF in $IFACES
      do
         /sbin/wpa_dhcp $IF stop
      done
  ;;
  *help)
    echo "Usage: $0 start | stop to start or stop all interfaces"
    echo "Use wpa_dhcp if0 stop to stop one interface"
  ;;
esac

